### ISSUE TITLE
Clarification on the Use of Decoy Database for Labeled Search in SIPROS 4

### ISSUE THREAD

**Issue by Harshita-Naithani** [thepanlab/SiprosToolKits#4]
I am currently using SIPROS 4 to quantify isotopic enrichment levels in my samples, and I came across a question regarding the use of the decoy database.

In the tutorial, the decoy database is created at the beginning of the process, but I noticed that it is not explicitly mentioned for use during either the unlabeled or labeled searches later on. However, while reviewing the Sipros4 > configTemplates > SiprosEnsembleConfig.cfg for the unlabeled search, I observed that the decoy database is included, even though it was not mentioned in the script.
For the labeled search, though, I found that the Sipros4 > configTemplates > SiprosV4Config.cfg does not include the decoy database, either in the script or the configuration file. I was wondering if the decoy database is not necessary for the labeled search, or should it be included in the configuration file?

I would greatly appreciate any guidance on this matter to ensure I am following the correct procedure.

**Comment by xyz1396** [comment]
the decoy database is not necessary for the labeled search because sipros will generate a decoy by itself when searching.

**Comment by Harshita-Naithani** [comment]
Great, thank you so much for the clarification.
